### ISSUE TITLE
[mathspeak] modifying above check is not "written out"

### ISSUE THREAD

**Issue by pkra** [Speech-Rule-Engine/speech-rule-engine#274]
While `$\acute{J}$` will give `ModifyingAbove upper J With acute`, I noticed that
`$\check{I}$` gives `ModifyingAbove upper I With ˇ`. 

The `ˇ` will be not be voiced in most screenreaders (with default settings).

**Comment by zorkow** [comment]
The characters from [Spacing Modifier Letters](https://unicode-table.com/en/blocks/spacing-modifier-letters/) are still missing.

**Comment by pkra** [comment]
This was fixed years ago.
