### ISSUE TITLE
dasheD vs dashed

### ISSUE THREAD

**Issue by pkra** [Speech-Rule-Engine/speech-rule-engine#530]
I noticed, e.g., 

https://github.com/zorkow/speech-rule-engine/blob/3ceaee95ff1c639f9ee079e8fa2ea6986eb18525/src/mathmaps/en/symbols/math_arrows.js#L834

and other dashed arrows have "dasheD" while

https://github.com/zorkow/speech-rule-engine/blob/3ceaee95ff1c639f9ee079e8fa2ea6986eb18525/src/mathmaps/en/symbols/math_symbols.js#L7402

has "dashed".

Is this difference intentional?

FWIW, screenreaders will often read "dashedD" as if it was "dash D".

**Comment by zorkow** [comment]
Poor replacement in the mathspeak sets where in `sbrief` mode arrows are abbreviated as `R L D U` for right, left, down, up.

**Comment by pkra** [comment]
This was fixed years ago.
