### ISSUE TITLE
4.0.0-beta.1 unexpected (visual) changes

### ISSUE THREAD

**Issue by pkra** [Speech-Rule-Engine/speech-rule-engine#552]
`$\cdot \mathcal{O}_{\widetilde{X}}=\mathcal{L}\cdot \_{\widetilde{Z}}$ ` now missing proper horizontal spacing around cdot. 

In beta0

Mathspeak: "dot script upper O Subscript upper X overTilde Baseline equals script upper L dot normal bar upper Z overTilde"
Nemeth: "⠡⠈⠰⠠⠕⠰⠐⠠⠭⠣⠈⠱⠻⠀⠨⠅⠀⠈⠰⠠⠇⠡⠸⠐⠠⠵⠣⠈⠱⠻"

in beta 1

Mathspeak: "dot script upper O Subscript upper X overtilde Baseline equals script upper L dot bar upper Z overtilde",
Nemeth: "⠡⠈⠰⠠⠕⠰⠐⠠⠭⠣⠈⠱⠻⠐⠀⠨⠅⠀⠈⠰⠠⠇⠡⠸⠀⠐⠠⠵⠣⠈⠱⠻",

**Comment by zorkow** [comment]
This is related to the [new heuristic that reclassifies bar and tilde elements that are not accents](https://github.com/zorkow/speech-rule-engine/pull/547/commits/fddbce4e36c6c8ab3cae892b779bfa14698c9d76).
They should be reclassified as  operators rather than punctuation.

**Comment by pkra** [comment]
I believe this was fixed.

**Comment by pkra** [comment]
Actually, hard to tell -- MathJax v4-beta4 crashes on this now.

**Comment by pkra** [comment]
I've filed https://github.com/mathjax/MathJax/issues/3120. But this issue does seem fixed on the SRE end.
