### ISSUE TITLE
[4.0.0-beta.2] regression with mfrac

### ISSUE THREAD

**Issue by pkra** [Speech-Rule-Engine/speech-rule-engine#564]
Apologies for the vague title.

Minimal case`\frac{| a{b c}|^d}{}` -- SRE drops the empty mrow, creating failure.

However, the full example which led me here  does not have an empty second element: ` \begin{equation*} I_0(\alpha _{\varepsilon }{\Delta x}) \simeq T_0(\alpha _{\varepsilon }{\Delta x}) := 1+\frac{|\alpha _{\varepsilon }{\Delta x}|^2}{4}, \qquad \alpha _{\varepsilon }{\Delta x}\ll 1. \end{equation*}`

**Comment by pkra** [comment]
This regression seems to be for v4 pre-releases in general. (I must have missed it earlier.)

**Comment by pkra** [comment]
It's still older. I tested down to 3.2.0 and still got the issue.

**Comment by pkra** [comment]
Just to add: `\frac{{| a{b c}|}^d}{}` or `\frac{\left| a{b c}\right|^d}{}` avoids SRE choking on this.

**Comment by zorkow** [comment]
Turns out it was independent of the fraction but a problem of rewriting embellished fences. E.g., a minimal example was `{| a{b c}|}^d`.

**Comment by pkra** [comment]
I believe this has been fixed.
