### ISSUE TITLE
incomplete configuration causing some loss of whitespace in speech output

### ISSUE THREAD

**Issue by pkra** [Speech-Rule-Engine/speech-rule-engine#669]
I understand if this a won't-fix but I thought I'd share it in any case.

I was flummoxed over the weekend trying to figure out why something like `FU ( \\mathbf{t} )` was giving me `upper Fupper Uleft parenthesisboldtright parenthesis` (note the dropped whitespace).

Turns out my configuration was missing something:

```
  await sre.setupEngine({
    domain: 'mathspeak',
    style: 'default',
    locale: 'en',
    speech: 'deep',
    structure: true,
    mode: 'sync',
  });
```

namely, adding `modality: 'speech'` fixed the issue. 

Since the domain only allows this modality, maybe modality could be set automatically. But again, I understand if this isn't worth the trouble.

**Comment by zorkow** [comment]
Is it possible that you ran SRE with `modality: 'braille'` beforehand? Than the standard string separator would be `''`.

At the moment there is no automation that maps from locales or domains to modalities.

**Comment by pkra** [comment]
> Is it possible that you ran SRE with `modality: 'braille'` beforehand? 

Effectively, yes.

> Than the standard string separator would be `''`.
> At the moment there is no automation that maps from locales or domains to modalities.

Right. Maybe incomplete configurations could cause a warning. But that's a different issue.
